---
# tasks file for opdk-setup-status

- name: Collect All Status
  shell: "{{ all_status }}"
  register: results
  ignore_errors: yes
  when: opdk_version | version_compare('4.16.01', '<')

- name: Collect All Status
  shell: "{{ apigee_all }} status"
  register: results
  ignore_errors: yes
  when: opdk_version | version_compare('4.16.01', '>=')

- name: View All Status Results
  debug:
    var: results
