---
# tasks file for opdk-setup-status

- name: Collect All Status
  shell: "{{ all_status }}"
  register: results
  ignore_errors: yes
  when: opdk_version | version_compare('4.16.01', '<')

- name: Collect All Status
  shell: "{{ apigee_all }} status"
  register: results
  ignore_errors: yes
  when: opdk_version | version_compare('4.16.01', '>=')

- name: View All Status Results
  debug:
    var: results

- name: Obtain management server self report
  ignore_errors: yes
  opdk_server_self:
    server_type: 'ms'
    username: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'

- name: Obtain router server self report
  ignore_errors: yes
  opdk_server_self:
    server_type: 'router'
    username: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'

- name: Router self report
  debug:
    var: edge_router_self

- name: Obtain message processor server self report
  ignore_errors: yes
  opdk_server_self:
    server_type: 'mp'
    username: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'

- name: Message processor self report
  debug:
    var: edge_mp_self

- name: Obtain postgres server self report
  ignore_errors: yes
  opdk_server_self:
    server_type: 'ps'
    username: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'

- name: Postgres server self report
  debug:
    var: edge_ps_self

- name: Obtain qpid server self report
  ignore_errors: yes
  opdk_server_self:
    server_type: 'qs'
    username: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'

- name: Qpid server self report
  debug:
    var: edge_qs_self
